Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/xenial64"

  config.vm.define "VTApiDev+docker"
  config.vm.hostname = "vtapidev"
  config.vm.provider "virtualbox" do |v|
    v.name = "VTApiDev + Docker"
  end

  config.vm.provision :file, source: "../docker/Dockerfile", destination: "/tmp/vtapi-docker/Dockerfile"
  config.vm.provision :shell, path: "bootstrap.sh"
end